[package]
name = "pillow-config"
version = "0.1.0"
description = "Load configuration from pillow.toml to pillow framework"
edition = "2021"
readme = "./README.md"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
toml = "0.7.6"
