[app]
name = "pillow"
debug = false

[router.directory]
resources = "/resources"
views = "resources/views"
js = "resources/js"
css = "resources/css"

[server]
port = 3000
url = "http://localhost"
address = [127, 0, 0, 1]

[server.ssl]
cert = ""
key = ""

[database]
connection = "sqlite"
port = 3317
name = "pillow"
user = "root"
password = "root"
