[package]
name = "pillow"
version = "0.1.2"
edition = "2021"
authors = ["SummaryPuppet"]
description = "A minimalist web framework for rust"
keywords = ["web", "backend"]
categories = ["web-programming"]
license-file = "LICENSE"
homepage = "https://github.com/SummaryPuppet/pillow_framework"
documentation = "https://github.com/SummaryPuppet/pillow_framework"
repository = "https://github.com/SummaryPuppet/pillow_framework"
readme = "README.md"
publish = true
exclude = ["/resources"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
regex = "1.6.0"
serde_json = "1.0.87"
