[package]
name = "pillow"
version = "0.1.3"
edition = "2021"
authors = ["SummaryPuppet"]
description = "A minimalist web framework for rust"
keywords = ["web", "backend"]
categories = ["web-programming"]
license-file = "LICENSE"
homepage = "https://github.com/SummaryPuppet/pillow_framework"
docuentation = "https://github.com/SummaryPuppet/pillow_framework"
repository = "https://github.com/SummaryPuppet/pillow_framework"
readme = "README.md"
publish = true
exclude = ["/resources", "/public"]

[dependencies]
chrono = "0.4.22"
clap = { version = "4.0.19", features = ["derive"] }
dotenv = "0.15.0"
regex = "1.6.0"
serde_json = "1.0.87"
