[package]
name = "pillow"
version = "0.1.0"
edition = "2021"
authors = ["SummaryPuppet"]
description = "A minimalist web framework for rust"
keywords = ["web", "backend"]
categories = ["web-programming"]
homepage = ""
documentation = ""
repository = "https://github.com/SummaryPuppet/sunny_framework"
readme = "README.md"
publish = false
exclude = ["/views"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.22"
serde_json = "1.0.87"
