[package]
name = "pillow-fs"
description = "pillow fs"
version.workspace = true
edition.workspace = true
authors.workspace = true
license = "MIT"
readme = "./README.md"
homepage.workspace = true
documentation.workspace = true
repository.workspace = true

[dependencies]

mime_guess = "2.0.4"