[package]
name = "pillow_templates"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
handlebars = "4.3.6"
serde_json = "1.0.91"
tera = "1.17.1"
pillow_fs = { path = "../fs" }
