[package]
name = "pillow_macros"
version = "0.1.0"
edition = "2021"
authors = ["SummaryPuppet"]
description = ""

[lib]
name = "pillow_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"
