[package]
name = "pillow"
version = "0.2.3"
edition = "2021"
authors = ["SummaryPuppet"]
description = "A web framework for rust"
keywords = ["web", "backend"]
categories = ["web-programming::http-server"]
license-file = "LICENSE"
homepage = "https://github.com/SummaryPuppet/pillow_framework"
documentation = "https://github.com/SummaryPuppet/pillow_framework"
repository = "https://github.com/SummaryPuppet/pillow_framework"
readme = "README.md"
publish = true
exclude = ["/resources", "/public"]



[dependencies]
mysql = "23.0.0"
postgres = "0.19.4"
serde = "1.0.148"
serde_json = "1.0.89"
pillow_http = { workspace = true, default-features = false, path = "../http" }
pillow_routing = { workspace = true, path = "../routing" }
pillow_fs = { workspace = true, path = "../fs" }
pillow_env = { workspace = true, path = "../env" }
colored = "2.0.0"

[dependencies.async-std]
version = "1.6"
features = ["attributes"]

[dependencies.uuid]
version = "1.2.2"
features = [
    "v4",
]
